name: Daily Snow Scraper

on:
  schedule:
    # 毎日午前6時（UTC）に実行
    - cron: '0 6 * * *'
  workflow_dispatch: # 手動実行を有効化
    inputs:
      run_reason: # 任意の理由を入力可能
        description: 'Reason for running the workflow'
        required: false

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウトコード
      uses: actions/checkout@v3

    - name: Pythonをセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 必要なパッケージをインストール
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas webdriver-manager

    - name: スクリプトを実行
      run: |
        python ss3.py

    - name: CSVファイルをアップロード
      uses: actions/upload-artifact@v3
      with:
        name: snow-info-data
        path: '*.csv'
