name: Daily Snow Scraper and Prediction

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前6時（UTC）に実行
  workflow_dispatch:  # 手動実行を許可

jobs:
  scrape-and-predict:
    runs-on: ubuntu-22.04

    steps:
    - name: チェックアウトコード
      uses: actions/checkout@v3

    - name: 必要なパッケージをインストール
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas webdriver-manager

    - name: Chromeをインストール
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: スクレイピングを実行
      run: |
        python ss4.py

    - name: 天気予測を実行
      run: |
        python predict_snow3.py

    - name: CSVファイルをアップロード
      uses: actions/upload-artifact@v4
      with:
        name: snow-and-weather-data
        path: |
          *_snow_info_data.csv
          *_weather_info.csv
