name: Daily Snow Scraper

on:
  schedule:
    - cron: '0 6 * * *'  # 毎日午前6時（UTC）に実行
  workflow_dispatch:  # 手動実行を許可

jobs:
  scrape:
    runs-on: ubuntu-22.04  # 現行のバージョンを明示的に指定

    steps:
    - name: チェックアウトコード
      uses: actions/checkout@v3

    - name: 必要なパッケージをインストール
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas webdriver-manager

    - name: Chromeをインストール
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: スクリプトを実行
      run: |
        python ss4.py  # 新しいスクリプト名に変更

    - name: CSVファイルをアップロード
      uses: actions/upload-artifact@v4  # v4に更新
      with:
        name: snow-info-data  # 成果物の名前
        path: '*.csv'  # yyyymmdd_snow_info_data.csv を含む全CSVをアップロード
